In [4]:
import polars as pl

dset = pl.read_parquet("../../data/sourced_antibody_v1/abdb_contigs.parquet")

In [ ]:
dset[:2].write_parquet(
    "/tgen_labs/altin/alphafold3/workspace/episcaf-experiments/data/Xsourced_antibody_v1/full_antibody/Xabdb_contigs.parquet"
)

In [5]:
dset[:2]

shape: (2, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ antigen_s ┆ heavy_seq ┆ light_seq ┆ epitope_s ┆ … ┆ contig_le ┆ epitope_c ┆ scaffolde ┆ scaffold │
│ eq        ┆ ---       ┆ ---       ┆ eq        ┆   ┆ ngth      ┆ hunk_resi ┆ d_epitope ┆ ed_epito │
│ ---       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ndices    ┆ _chunk_re ┆ pe_resin │
│ str       ┆           ┆           ┆ str       ┆   ┆ str       ┆ ---       ┆ sin…      ┆ dices    │
│           ┆           ┆           ┆           ┆   ┆           ┆ list[i64] ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ list[i64] ┆ list[i64 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CSMPLGMES ┆ QVQLVQSGA ┆ IALTQSPGT ┆ FTNMFRRQV ┆ … ┆ 104-104   ┆ [22, 23,  ┆ [14, 15,  ┆ [14, 15, │
│ KAISDAQIT ┆ EVKKPGASV ┆ LSLSPGERA ┆ SLLTMHQ   ┆   ┆           ┆ … 142]    ┆ … 89]     ┆ … 89]    │
│ ASSYFTNMF ┆ KVSCKVSGY ┆ TLSCRASQS ┆           ┆   ┆           ┆           ┆           ┆          │
│ ATW…      ┆ TLT…      ┆ FSS…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CSMPLGMES ┆ QVQLVQSGA ┆ IALTQSPGT ┆ FTNMFRRQV ┆ … ┆ 104-104   ┆ [22, 23,  ┆ [9, 10, … ┆ [9, 10,  │
│ KAISDAQIT ┆ EVKKPGASV ┆ LSLSPGERA ┆ SLLTMHQ   ┆   ┆           ┆ … 142]    ┆ 94]       ┆ … 94]    │
│ ASSYFTNMF ┆ KVSCKVSGY ┆ TLSCRASQS ┆           ┆   ┆           ┆           ┆           ┆          │
│ ATW…      ┆ TLT…      ┆ FSS…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
dset[:2].write_parquet(
    "/tgen_labs/altin/alphafold3/workspace/episcaf-experiments/data/Xsourced_antibody_v1/Xabdb_contigs.parquet"
)

In [ ]:
pl.read_parquet(
    "/tgen_labs/altin/alphafold3/workspace/episcaf-experiments/data/Xsourced_antibody_v1/Xabdb_contigs.parquet"
).select("contig_string")[0].item()

'14-14/A23-27/23-23/A42-50/24-24/A77-82/7-7/A142-143/14-14/0 B1-117/0 C1-110/0 '

In [ ]:
import numpy as np
import pickle

with open(
    "/tgen_labs/altin/alphafold3/workspace/episcaf-experiments/data/Xsourced_antibody_v1/rfdiffusion/1iqd_0P/1/1iqd_0P_1.trb",
    "rb",
) as f:
    trb = pickle.load(f)

In [24]:
trb["inpaint_seq"]

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [ ]:
pl.read_parquet(
    "/tgen_labs/altin/alphafold3/workspace/episcaf-experiments/data/Xsourced_antibody_v1/scaffold_summary.parquet"
)

shape: (160, 27)
┌────────────┬────────────┬────────────┬────────────┬───┬────────┬─────────┬───────────┬───────────┐
│ antigen_se ┆ heavy_seq  ┆ light_seq  ┆ epitope_se ┆ … ┆ rfd_id ┆ mpnn_id ┆ scaffolde ┆ scaffolde │
│ q          ┆ ---        ┆ ---        ┆ q          ┆   ┆ ---    ┆ ---     ┆ d_epitope ┆ d_epitope │
│ ---        ┆ str        ┆ str        ┆ ---        ┆   ┆ i64    ┆ i64     ┆ _seq      ┆ _chunk_re │
│ str        ┆            ┆            ┆ str        ┆   ┆        ┆         ┆ ---       ┆ sin…      │
│            ┆            ┆            ┆            ┆   ┆        ┆         ┆ str       ┆ ---       │
│            ┆            ┆            ┆            ┆   ┆        ┆         ┆           ┆ list[i64] │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════╪═════════╪═══════════╪═══════════╡
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 0      ┆ 0       ┆ KLEKVFVAP ┆ [14, 15,  │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ LGMKPFTNM ┆ … 89]     │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ FNEYEVYTA ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ TDK…      ┆           │
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 0      ┆ 1       ┆ SLEKVFLAP ┆ [14, 15,  │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ KGMKPFTNM ┆ … 89]     │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ FNEYEVAEV ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ TRA…      ┆           │
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 0      ┆ 2       ┆ ELVKYAKVP ┆ [14, 15,  │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ LGMKPFTNM ┆ … 89]     │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ FNEYEVFEV ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ TDE…      ┆           │
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 0      ┆ 3       ┆ SLTKVVKTP ┆ [14, 15,  │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ KGMKPFTNM ┆ … 89]     │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ FNEAKVFTA ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ TDA…      ┆           │
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 0      ┆ 4       ┆ KLKKVAKVP ┆ [14, 15,  │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ KGMKPFTNM ┆ … 89]     │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ FNEYTVADV ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ TDK…      ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …      ┆ …       ┆ …         ┆ …         │
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 9      ┆ 3       ┆ TTVTVTTTE ┆ [9, 10, … │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ FTNMFLDLD ┆ 94]       │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ VATAATQKR ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ SNA…      ┆           │
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 9      ┆ 4       ┆ TTVNITTNY ┆ [9, 10, … │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ FTNMFMDLD ┆ 94]       │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ VETAADQKR ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ SNA…      ┆           │
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 9      ┆ 5       ┆ TTVNITTNQ ┆ [9, 10, … │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ FTNMFLDLD ┆ 94]       │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ VDTAANQVR ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ SNA…      ┆           │
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 9      ┆ 6       ┆ TTVTVTTTQ ┆ [9, 10, … │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ FTNMFMDLD ┆ 94]       │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ IDTAADQKR ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ SNA…      ┆           │
│ CSMPLGMESK ┆ QVQLVQSGAE ┆ IALTQSPGTL ┆ FTNMFRRQVS ┆ … ┆ 9      ┆ 7       ┆ KTVNITTNE ┆ [9, 10, … │
│ AISDAQITAS ┆ VKKPGASVKV ┆ SLSPGERATL ┆ LLTMHQ     ┆   ┆        ┆         ┆ FTNMFLNLD ┆ 94]       │
│ SYFTNMFATW ┆ SCKVSGYTLT ┆ SCRASQSFSS ┆            ┆   ┆        ┆         ┆ VATAKDQKR ┆           │
│ …          ┆ …          ┆ …          ┆            ┆   ┆        ┆         ┆ SNA…      ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴────────┴─────────┴───────────┴───────────┘